### ISSUE TITLE
clone_from progress is broken in newer version

### ISSUE THREAD

**Issue by Dreamsorcerer** [gitpython-developers/GitPython#604]
To use a workaround for another bug, I had to first update GitPython. After updating with `pip3 install --upgrade gitpython`, which installed 2.1.3, the progress feature no longer functions correctly.

With this code:

```
import git
def u(*args):
 print(args, flush=True)
git.Repo.clone_from("git@bitbucket.org:....", ".", u)
```

While running it on a fairly large repository, I get the first few updates, upto:
`(10, 16118.0, 16118.0, '')` (which means compressing has completed)

But, then the next stage when it is downloading everything, which can take about 15 mins, there is no feedback until it has completed that stage, then all the missing feedback is sent at once, as if the feedback has gathered in a buffer and not sent until the current stage is complete.

**Comment by Dreamsorcerer** [comment]
OK, I've narrowed it down through trial and error.
Working correctly: 2.0.8
Broken: 2.0.9

**Comment by Byron** [comment]
Thanks for narrowing it down!
I had a closer look and found [this commit](https://github.com/gitpython-developers/GitPython/commit/85f38a1bbc8fc4b19ebf2a52a3640b59a5dcf9fe) which simplified the code to just-in-time parse lines from stdout and/or stderr.

To me the code looks good - the main thread blocks while lines are read from streams as they become available. Apparently [this line iteration](https://github.com/gitpython-developers/GitPython/blob/3ef889531eed9ac73ece70318d4eeb45d81b9bc5/git/cmd.py#L83) doesn't work as expected for you.

Can you provide more information about your environment as it may relate to the issue:

* the exact python version
* the OS

Thanks  a lot

**Comment by Dreamsorcerer** [comment]
Python 3.5.2
Ubuntu 16.04

**Comment by Dreamsorcerer** [comment]
Any progress on this? Have you been able to reproduce it? It should be trivial to test in a vagrant box or similar.

This is causing us some fairly bad UX issues in our project at the moment.

Full steps to reproduce:
Install Vagrant.
Save the attached Vagrantfile into a new folder (you'll need to remove the .txt extension thanks to Github's dumb mimetype detection).
[Vagrantfile.txt](https://github.com/gitpython-developers/GitPython/files/1148776/Vagrantfile.txt)

Run `vagrant up && vagrant ssh`
Inside the vagrant box:
```
sudo apt update
sudo apt install python3-pip -y
pip3 install gitpython
ssh-keyscan github.com > ~/.ssh/known_hosts
python3
```

```
import git
def u(*args):
 print(args, flush=True)

git.Repo.clone_from("https://github.com/gitpython-developers/GitPython.git", "test", u)
```

**Comment by RenanMsV** [comment]
Stills broken. Works in 2.0.8.
I'm using standard Progress class.
`class Progress(RemoteProgress):
    def update(self, op_code, cur_count, max_count=None, message=''):
        print('Baixando: (==== {} ====)\r'.format(message))`
and then calling it
`Repo.clone_from("git://github.com/{}".format(link.split('.com/')[1]), PATH_NAME, progress=Progress())`

**Comment by Byron** [comment]
Could you try it again with the latest version?

**Comment by RenanMsV** [comment]
working 2.1.7

**Comment by Dreamsorcerer** [comment]
Nope, no change. Followed my exact steps mentioned a couple of comments ago, and got exactly the same problem. GitPython==2.1.7
https://github.com/gitpython-developers/GitPython/issues/604#issuecomment-315380251

**Comment by Minipada** [comment]
I have exactly the same, seems similar than #444. Using 2.1.7

**Comment by Dreamsorcerer** [comment]
Confirmed, this is the same problem, and is fixed by following @mrozekma's comment:
I fixed it locally by changing `git.remote.add_progress` to also set `kwargs['universal_newlines'] = True`, and changing `git.base.Repo._clone` to pass `decode_streams=False` to `handle_process_output`

**Comment by Dreamsorcerer** [comment]
I made a tweak to those instructions to fix build issues in the referenced pull request, though there are still a couple of build errors which mean nothing to me.

**Comment by Dreamsorcerer** [comment]
Actually, it looks like the remaining build issues also exist in the main branch. So, please review and merge.

**Comment by Byron** [comment]
@Dreamsorcerer I am closing this issue as its fix will be contained in the upcoming release.

**Comment by jjloesch** [comment]
Still broken in 2.1.8
Reverting to last known working version 2.0.8

**Comment by Dreamsorcerer** [comment]
Are you following my exact instructions in my previous comment https://github.com/gitpython-developers/GitPython/issues/604#issuecomment-315380251? I've just tested it again following those exact instructions, and it it is working correctly. If you are encountering an issue in a different situation, then it is a different bug, please file a new one.
