### ISSUE TITLE
Module requirments use gitdb2 and in compat importing gitdb instead

### ISSUE THREAD

**Issue by mell0** [gitpython-developers/GitPython#983]
Requirments file includes gitdb2 and, but "compat.py" file is importing "gitdb" instead and throwing missing "gitdb" module error when this library is fresh installed in a new enviroment with missing "gitdb" dependency library. Please fix the problem.

**Comment by davidwneary** [comment]
Experiencing the same here. 
```
from gitdb.utils.compat import (
 ModuleNotFoundError: No module named 'gitdb.utils.compat'
```

We're using the `3.0.5` release. Looks like the latest release to gitdb (3.0.2) has caused the issue - if I add `gitdb2==3.0.1` to my requirements.txt, it's fixed.

**Comment by Harmon758** [comment]
Ah, the issue is that GitDB v3.0.2 removed `gitdb.utils.compat`.
I'll push a fix momentarily.

`gitdb2` is the same `gitdb` library renamed on PyPI due to loss of access to the original PyPI account.
See https://github.com/gitpython-developers/gitdb/issues/45, https://github.com/gitpython-developers/gitdb/issues/47, and https://github.com/pypa/pypi-support/issues/204.
The import remains `gitdb`.

**Comment by Harmon758** [comment]
@davidwneary Actually, that import was removed with v3.0.6. This should be resolved in the latest versions.

**Comment by Harmon758** [comment]
@mell0 I'm unable to reproduce this in a new environment with the latest versions of both libraries, i.e. gitpython v3.0.8 and gitdb2 v3.0.2. If your issue is different, can you provide the details of your environment, e.g. gitpython, gitdb2, and python versions, and the full traceback?

**Comment by mell0** [comment]
Hi,

Problem is when trying to install an older version for GitPython which I had in my test requirements file, to be specific v3.0.4. I understood that this was fixed in versions above v3.0.6.  It's just that v3.0.4 should have used in its requirements working gitdb2 version with compat included, because now I have a lot of deployment fails of my apps and I'm sure it's not only me. In my opinion requirements should contain more specific version of the dependencies not just >=, because thus way people using older version and relying on it are suffering and in general at the moment older versions <=v3.0.6 are not working.

**Comment by mell0** [comment]
To reproduce, just create new virtual env, try to install GitPython==3.0.4, and try to import it.

**Comment by Harmon758** [comment]
I agree that the versioning is less than ideal here. In fact, GitPython shouldn't have been using GitDB compatibility shims in the first place, causing the removal to be a breaking change, as they should have been internal rather than exposed. 

I've gone ahead and restricted the gitdb2 version to < 4 now with https://github.com/gitpython-developers/GitPython/commit/e81fd5447f8800373903e024122d034d74a273f7 to mitigate future issues like this, and it should be part of the next release.

However, there's not much that can be done at this point for older versions that rely on gitdb2 < 3.0.2. Even if the GitDB removal was reverted, since it wasn't restricted to < or <= any certain version for GitPython, any breaking change in the future would still break older GitPython versions.
But since the only GitPython version requirement for gitdb2 was >= 2 for older versions, you can simply specify gitdb2 < 3.0.2 in your own dependencies if you want to continue using an older version of GitPython.

In fact, [there was an issue with the formatting of the version specifier that wasn't fixed until GitPython v3.0.6](https://github.com/gitpython-developers/GitPython/commit/2573dd5409e3a88d1297c3f9d7a8f6860e093f65), so you should be able to specify and install any gitdb2 version (although I can't guarantee that it'll work with < 2). It's just that, by default, the latest version will be installed.

**Comment by fmigneault** [comment]
@Harmon758 
You could do a post release (https://www.python.org/dev/peps/pep-0440/#post-releases).
An hotfix for such a thing would avoid many unexpected problems by devs that tagged this version in order to have stable code, but suddenly still get an error.

I would also argue that using the patch number instead of (at least) minor for such big refactoring isn't really a best practice to avoid situations like this in the future.

**Comment by mitar** [comment]
When can we expect this next release?

**Comment by Harmon758** [comment]
I don't think creating a post-release for this is a good idea. As PEP 440 says, it's meant for issues that don't affect the actual software, like changes in release notes, and shouldn't be used for actual bug fixes. In addition, to cover every old version affected by the issue, we'd have to do 9 post-releases for 2.1.12 - 2.1.14 and 3.0.0 - 3.0.5.

I agree that some of the recent releases should have been minor version bumps rather than patch version bumps, but [I've only very recently become a maintainer](https://github.com/gitpython-developers/GitPython/pull/979#issuecomment-583701599) and Byron has been doing the releases. We're still working on our development and release process, but we have an open line of communication now that should help.

Apologies for any hassles this issue might have caused, but the root cause of the issue is that gitdb2 was not version locked. Having a minor version bump instead of a patch version bump wouldn't have affected the issue at all. In fact, any breaking change in GitDB, even with a major version bump, would have had the potential of breaking old GitPython versions.

Future issues like this should be mitigated now with gitdb2 version-locked to < 4. If an unintentional breaking change in a patch version bump were to occur again, we could simply revert the change in another patch version bump and release it with a major version bump.

As for resolving the current issue, if you're using an older version of GitPython, you can simply upgrade to the latest version of either major version, i.e. 3.0.8 or 2.1.15. Upgrading to 3.0.6 or 3.0.7 should resolve the issue as well. If you need to use an older version and can't upgrade, you'll have to add a requirement for gitdb2 < 3.0.2.

**Comment by Byron** [comment]
And should it become necessary, we might even be able to fight fire with fire, and **overwrite** a previous release of gitdb. 
Personally I would prefer the affected folks to upgrade, but arguments can be made for the alternative above.

**Comment by elliottb303** [comment]
I bumped up to 3.0.8; didn't solve problem for me. Not sure if docker is caching something locally.

Using gitdb2==3.0.1 was solution for me. 


Do I need a pip force upgrade?? Also very strange, this was working all last night no issues, then this AM the issue popped up without any changes to my project requirements.txt.

Thanks!

project requirements:

#Django==1.11.5
Django==2.2
psycopg2-binary
djangorestframework>=3.11.0
pyjwt
gunicorn
pyyaml
jinja2
coreapi

celery>=4.4.0
redis>=3.3.1
kombu>=4.6.7

GitPython>=3.0.8
gitdb2==3.0.1

**Comment by Harmon758** [comment]
> That import was removed with GitPython v3.0.6 (https://github.com/gitpython-developers/GitPython/commit/b5dd2f0c0ed534ecbc1c1a2d8e07319799a4e9c7, https://github.com/gitpython-developers/GitPython/commit/a10ceef3599b6efc0e785cfce17f9dd3275d174f, https://github.com/gitpython-developers/GitPython/commit/5d22d57010e064cfb9e0b6160e7bd3bb31dbfffc) so the latest versions shouldn't have that issue.

https://github.com/gitpython-developers/GitPython/issues/983#issuecomment-586947523

Please provide a full traceback if you can somehow reproduce this with v3.0.8.

**Comment by Byron** [comment]
GitPython 3.1.0 was just released, which probably doesn't help in this particular case but marks a milestone towards bringing it back to a normal, _stable_ state with code and dependencies cleaned up considerably.

The solution to the import errors can be found [in this comment](https://github.com/gitpython-developers/GitPython/issues/983#issuecomment-587336153).

**Comment by elliottb303** [comment]
> > That import was removed with GitPython v3.0.6 ([b5dd2f0](https://github.com/gitpython-developers/GitPython/commit/b5dd2f0c0ed534ecbc1c1a2d8e07319799a4e9c7), [a10ceef](https://github.com/gitpython-developers/GitPython/commit/a10ceef3599b6efc0e785cfce17f9dd3275d174f), [5d22d57](https://github.com/gitpython-developers/GitPython/commit/5d22d57010e064cfb9e0b6160e7bd3bb31dbfffc)) so the latest versions shouldn't have that issue.
> 
> [#983 (comment)](https://github.com/gitpython-developers/GitPython/issues/983#issuecomment-586947523)
> 
> Please provide a full traceback if you can somehow reproduce this with v3.0.8.
> 
> Also, note, PyPI does not allow overwriting of releases, so that won't be happening.

I reset all docker caches, and still seeing the compat tools error, using the latest 3.1.0. 

Skipping of compat upgrade during install:

Step 13/14 : RUN pip install --upgrade gitpython
 ---> Running in ada164e19169
Requirement already up-to-date: gitpython in /usr/local/lib/python3.8/site-packages (3.1.0)
Requirement already satisfied, skipping upgrade: gitdb<5,>=4.0.1 in /usr/local/lib/python3.8/site-packages (from gitpython) (4.0.2)
Requirement already satisfied, skipping upgrade: smmap<4,>=3.0.1 in /usr/local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython) (3.0.1)

..
then normal error:

celery_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
celery_1       |   File "/opt/services/api/src/api/api/urls.py", line 15, in <module>
celery_1       |     from apps.views import ApplicationViewSet, RepoViewSet, RepoScanAPIView, ProjectRepoScanAPIView, ProjectViewSet
celery_1       |   File "/opt/services/api/src/api/apps/views.py", line 24, in <module>
celery_1       |     from .tasks import repo_scan, project_scan
celery_1       |   File "/opt/services/api/src/api/apps/tasks.py", line 20, in <module>
celery_1       |     from git import Repo as gitRepo
celery_1       |   File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 38, in <module>
celery_1       |     from git.exc import *                       # @NoMove @IgnorePep8
celery_1       |   File "/usr/local/lib/python3.8/site-packages/git/exc.py", line 9, in <module>
celery_1       |     from git.compat import UnicodeMixin, safe_decode, string_types
celery_1       |   File "/usr/local/lib/python3.8/site-packages/git/compat.py", line 16, in <module>
celery_1       |     from gitdb.utils.compat import (
celery_1       | ModuleNotFoundError: No module named 'gitdb.utils.compat'


I will revert to pinning  gitdb2==3.0.1 .

My full reqs.txt is commented above for info. Any suggestions greatly appreciated

**Comment by elliottb303** [comment]
For anyone dealing with this issue and other python3 issues - here is my docker workaround, including workaround for similar shenanigans with django-celery-beat ( waiting for maintainer to release new version )

....
RUN pip install -r requirements.txt
RUN pip install https://github.com/celery/django-celery-beat/zipball/master#egg=django-celery-beat
RUN pip install gitdb2==3.0.1
...

**Comment by Harmon758** [comment]
If you're using GitPython v3.1.0, you'll want to only install gitdb >= 4.0.1 and not gitdb2, as that version switches back to using the gitdb package name and requires gitdb >= 4.0.1. See https://github.com/gitpython-developers/gitdb/issues/59. gitdb2 is now simply a mirror package with v4.0.2. Installing an older version of gitdb2 along with gitdb >= 4.0.1 could very likely cause issues, since both are instances of the same library with the same name.

**Comment by elliottb303** [comment]
@Harmon758 I see. I switched to gitdb2. Thanks!

**Comment by jsrice7391** [comment]
I ran into the same issue. I uninstalled GitPython and then reinstalling it to get past the original error and then I ended up pinning the GitPython version higher than 3.1.0 and a fully successful build.

**Comment by mmaithani** [comment]
> Experiencing the same here.
> 
> ```
> from gitdb.utils.compat import (
>  ModuleNotFoundError: No module named 'gitdb.utils.compat'
> ```
> 
> We're using the `3.0.5` release. Looks like the latest release to gitdb (3.0.2) has caused the issue - if I add `gitdb2==3.0.1` to my requirements.txt, it's fixed.

yeah 3.0.1 worked for me too, Thanks !
